### ISSUE TITLE
finishActivity

### ISSUE THREAD

**Issue by tanweis** [DylanCaiCoding/Longan#12]
fun <T : Activity> finishActivity(clazz: KClass<T>): Boolean =
  activityCache.removeAll {
    if (it.javaClass == clazz) it.finish()
    it.javaClass == clazz
  }
这个函数不执行，Kclass和javaClass并不相等

**Comment by DylanCaiCoding** [comment]
感谢反馈，这里是比较了两个 Java Class，当时忘了比较 Class 是判断是不是同一个对象，而这是两个 Class 对象所以走了 false。其实后面发现问题了，但是改的时候改漏了...

**Comment by DylanCaiCoding** [comment]
已发 1.1.1 版本修复该问题，更新日志：https://github.com/DylanCaiCoding/Longan/releases/tag/1.1.1
