### ISSUE TITLE
checkPermission返回值意义有争议

### ISSUE THREAD

**Issue by xuhaoyang** [DylanCaiCoding/Longan#13]
ActivityCompat.checkSelfPermission(this, permission) != PackageManager.PERMISSION_GRANTED
代表没有权限为为true，但仅看checkPermission，惯性思维应该是true为有权限吧

能否进行修改呢？thk

**Comment by DylanCaiCoding** [comment]
感谢反馈，个人多数是使用 [ActivityResult API 的方法](https://dylancaicoding.github.io/Longan/#/usage/permissions)检测加请求权限，没注意之前敲错了。

然后个人思考了下，决定把 `Context.checkPermission(permission)` 的扩展函数改成 `Context.isPermissionGranted(permission)`，因为官方的 `checkSelfPermission(permission)` 返回一个 Int 类型，如果使用类似的扩展却返回 Boolean，会让一些小伙伴读源码时感到疑惑。改成 `isPermissionGranted(permission)` 能与官方用法作区分，并且能从函数名看得出返回值是 Boolean。

由于前几天已经发了个 1.1.0 版本，这个等过两天稍微补点工具类再一起修复发个新版，到时会通知您。

**Comment by DylanCaiCoding** [comment]
已发 1.1.1 版本修复该问题，更新日志：https://github.com/DylanCaiCoding/Longan/releases/tag/1.1.1
