### ISSUE TITLE
希望加入一些功能

### ISSUE THREAD

**Issue by NeVaDaAAA** [DylanCaiCoding/Longan#15]
比如判断图片类型、保存图片到图库等功能
我这边有个颜色的ext, 希望可以加进去
val String.color: Int
    get() = try {
        Color.parseColor(this)
    } catch (e: Exception) {
        Color.WHITE
    }

**Comment by DylanCaiCoding** [comment]
这个函数在 Resource.kt 里有封装，用法是 `parseColor("#ff0000")` 节省个类名，可以改成 `String.paresColor()`。用 `color` 扩展属性感觉会有点奇怪，不是所有字符串都能拿到颜色。

判断图片类型可以试下 `File.mimeType`，也有[拍照保存图片到图库](https://dylancaicoding.github.io/Longan/#/usage/activityresult?id=%e6%8b%8d%e7%85%a7)的功能，基于 ActivityResult 实现的。如果还不满足，可以再描述下具体的需求，我会考虑封装一下。

**Comment by NeVaDaAAA** [comment]
OK 感谢
