### ISSUE TITLE
doOnClick方法

### ISSUE THREAD

**Issue by BaiMingxu** [DylanCaiCoding/Longan#17]
大佬clickIntervals有默认值么？每次都要传500

**Comment by DylanCaiCoding** [comment]
最近加了个 `View.doOnDebouncingClick {...}`，老代码会弃用的横线，使用 alt + enter 能一键替换，然后可以全局把 500 的参数给移除了。设置 `debouncingClickIntervals` 属性可以修改默认间隔。

你可以先用快照版本，这是最新的代码。正式版会再加点工具类再发，到时换个依赖就行，发了新版我会通知您。

```
implementation 'com.github.DylanCaiCoding.Longan:longan:-SNAPSHOT'
```

**Comment by BaiMingxu** [comment]
好的，谢谢您
