### ISSUE TITLE
Failed to resolve: com.github.DylanCaiCoding.Longan:longan:1.1.1

### ISSUE THREAD

**Issue by hujingting** [DylanCaiCoding/Longan#21]
Android Studio Dolphin 版本

pluginManagement {
    repositories {

        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }

        maven { url 'https://www.jitpack.io' }

        gradlePluginPortal()
        google()
        mavenCentral()
    }

    plugins {
        id 'com.android.application' version '7.3.0'
        id 'com.android.library' version '7.3.0'
        id 'org.jetbrains.kotlin.android' version '1.7.10'
    }

}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "FreeSearch"
include ':app'

**Comment by Linnnnnn** [comment]
在dependencyResolutionManagement 块下增加maven仓库地址

**Comment by hujingting** [comment]
> 在dependencyResolutionManagement 块下增加maven仓库地址

谢谢
