### ISSUE TITLE
日期时间天数星期等转换的支持

### ISSUE THREAD

**Issue by BaiMingxu** [DylanCaiCoding/Longan#6]
非常好用，感谢大佬。希望有时间能添加日期时间的相互转换

**Comment by DylanCaiCoding** [comment]
其实在 Q&A 里有写，推荐用 Kotlin 官方的日期时间库。我之前有用 Java8 的 LocalDateTime 封装，后来发现和官方库类似就移除了。链接：https://github.com/Kotlin/kotlinx-datetime

要不迟点我在文档里补个 `kotlinx-datetime` 的用法，不然看到没日期时间工具挺奇怪的。

**Comment by BaiMingxu** [comment]
感谢
