### ISSUE TITLE
建议：补全一些工具类，例如Spanutil

### ISSUE THREAD

**Issue by Power-Android** [DylanCaiCoding/Longan#7]
我列举一些我开发常用的，如 Spanutil，Gsonutil，imageUtil，permissionUtil， TimeUtil加一下最好，不太想多引个包进来。感谢作者

**Comment by DylanCaiCoding** [comment]
感谢反馈，请问 ImageUtil 是有些什么功能？权限工具在 [ActivityResult](https://dylancaicoding.github.io/Longan/#/usage/activityresult?id=%e8%af%b7%e6%b1%82%e5%8d%95%e4%b8%aa%e6%9d%83%e9%99%90) 里。

其它的是看到官方库有，我就没封装或者把封装好的删了。我迟点把这部分的使用文档也补上吧，不然有些人不知道。

SpanUtil 的功能在 `core-ktx` 有，用法是：

```kotlin
textView.text = buildSpannedString {
   bold { italic { append("baidu") } }
}
```

Json 工具可以选择  [kotlinx-serialization](https://github.com/Kotlin/kotlinx.serialization) 或者 [moshi](https://github.com/square/moshi)。

 日期工具推荐用官方的 [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime)。
