### ISSUE TITLE
startIntentSenderLauncher.launch(intentSender) 使用方法

### ISSUE THREAD

**Issue by luowenyue** [DylanCaiCoding/Longan#8]
文档中使用方法如下：
```
val startIntentSenderLauncher = startIntentSenderLauncher {
  if (it.resultCode == Result_OK) {
    // 处理结果
  }
}

startIntentSenderLauncher.launch(intentSender) 
```
但实际写startIntentSenderLauncher.launch(intentSender) 报错，
Not enough information to infer type variable T
因为这个launch方法是这样的：launch<T:Activity>(intentSender) 
很让人疑惑，请指教

**Comment by DylanCaiCoding** [comment]
感谢反馈，泛型是写多了，我迟点改一下。先不要用这个扩展，改回原本 ActivityResult API 的 launch 用法。

```kotlin
startIntentSenderLauncher.launch(IntentSenderRequest.Builder(intentSender).builder())
```

**Comment by DylanCaiCoding** [comment]
抱歉，因为 ActivityResult 和时间日期的用法改动较大，之前又比较忙，所以新版拖得比较久。目前已经在 1.1.0 修复了该问题，原有的 xxxxLauncher 函数名将改成了 registerForXXXXResult，这样和官方 API 的用法更加一致。

更新日志：https://github.com/DylanCaiCoding/Longan/releases/tag/1.1.0
ActivityResult 文档：https://dylancaicoding.github.io/Longan/#/usage/activityresult
